# Generated by Django 4.0.3 on 2022-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_shopuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалён'),
        ),
    ]
